image: php:8.1

before_script:
  - apt-get update -yqq && apt-get install git libzip-dev zlib1g-dev -yqq
  - docker-php-ext-install pdo pdo_mysql zip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - pecl channel-update pecl.php.net
  - pecl install xdebug

services:
  - mysql

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: guestbook
  GUESTBOOK_DB_DSN: mysql:dbname=guestbook;host=mysql
  GUESTBOOK_DB_USER: root
  GUESTBOOK_DB_PASSWORD: root

Test:
  script:
    - ./bin/wait-for-it.sh mysql:3306
    - php bin/load-schema.php
    - composer test
