before_script:
  - bash ci/gitlab/docker_install.sh
  - php -v
  - php bin/load-schema.php
  - composer install

services:
  - mysql

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: guestbook
  GUESTBOOK_DB_DSN: mysql:dbname=guestbook;host=mysql
  GUESTBOOK_DB_USER: root
  GUESTBOOK_DB_PASSWORD: root

test:5.6:
  image: php:5.6
  script:
    - composer test

test:latest:
  image: php
  script:
    - composer test
