stages:
  Build:
    Composer install:
      docker:
        composer:
          image: composer/composer
          volumes:
            - .:/app
      commands:
        - composer install --no-scripts --ignore-platform-reqs

  Tests:
    Unit Tests:
      docker:
        php:
          image: php
          volumes:
            - .:/app
          links:
            - mysql
          environment:
            DB_DSN: mysql:dbname=guestbook;host=mysql
            DB_USER: root
            DB_PASSWORD: root
        mysql:
          image: mysql
          environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: guestbook
      commands:
        # Install MySQL (should be done before in an own CI PHP image...)
        - docker-php-ext-install pdo pdo_mysql

        #
        - php -v
        - cd /app
        - ./bin/wait-for-it.sh mysql:3306
        - php bin/load-schema.php
        - php vendor/bin/phpunit
