language: php

services:
  - mysql

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - GUESTBOOK_DB_DSN="mysql:dbname=guestbook;host=localhost" GUESTBOOK_DB_USER=root GUESTBOOK_DB_PASSWORD=""

before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS guestbook;"
  - mysql guestbook < ./etc/schema.sql
  - composer self-update
  - composer install

script: composer test

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - mkdir -p build/logs
  - travis_retry php coveralls.phar -x build/coverage.xml
