language: php

services:
  - mysql

php:
  - hhvm
  - 5.6
  - 7.0

env:
  - DB_DSN="mysql:dbname=guestbook;host=localhost" DB_USER=root DB_PASSWORD=""

before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS guestbook;"
  - mysql guestbook < ./etc/schema.sql
  - composer self-update
  - composer install

script: composer test

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - mkdir -p build/logs
  - travis_retry php coveralls.phar -x build/coverage.xml
