language: php

services:
  - mysql

php:
  - 7.3
  - 7.4

env:
  global:
    - CC_TEST_REPORTER_ID=ea7b390e89463c4fdec0b3897e0d2bd0dee94a19677a7a84270b9b140c84a675
  matrix:
    - GUESTBOOK_DB_DSN="mysql:dbname=guestbook;host=localhost" GUESTBOOK_DB_USER=root GUESTBOOK_DB_PASSWORD=""

script:
  # Code Climate before script (installs test reporter)
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

  # Setup database
  - mysql -e "CREATE DATABASE IF NOT EXISTS guestbook;"
  - mysql guestbook < ./etc/schema.sql

  # Install composer dependencies
  - make test

after_success:
  # Report code coverage to coveralls
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - mkdir -p build/logs
  - travis_retry php coveralls.phar -x build/logs/clover.xml

  # Report test result to Code Climate
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t clover
