build: false
shallow_clone: false
platform: 'x86'
clone_folder: C:\projects\guestbook
init:
  - SET PATH=C:\tools\php\;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
install:
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - cd C:\projects\guestbook
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-dist --no-interaction
test_script:
  - cd C:\projects\guestbook
  - php composer.phar test
