www:
  build: ./etc/php
  volumes:
    - .:/var/www/html
  links:
    - mysql
  ports:
    - "80:80"
  environment:
    GUESTBOOK_DB_DSN: mysql:dbname=guestbook;host=mysql
    GUESTBOOK_DB_USER: db_user
    GUESTBOOK_DB_PASSWORD: db_password

mysql:
  image: mysql
  volumes:
    - ./etc/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    - ./etc/fixtures.sql:/docker-entrypoint-initdb.d/02-fixtures.sql
  environment:
    MYSQL_ROOT_PASSWORD: a_secret
    MYSQL_DATABASE: guestbook
    MYSQL_USER: db_user
    MYSQL_PASSWORD: db_password
